"""Derive an eval set from a fetched corpus manifest.

`eval/labels.json` is hand-authored: someone looked at the frames and wrote
down what is in them. That does not scale to two hundred clips, and the
manifest already carries a human-written description of each one -- the
uploader's own title, in the URL slug.

**These labels are weak supervision and must stay labelled as such.** Nobody
checked them against the frames. A slug can be wrong, stale, or describe a
detail that never appears. That noise is tolerable for what this set is for --
*comparing* two configurations of the engine, where a paired comparison over
identical queries cancels per-query difficulty -- and not tolerable as an
absolute claim about quality. The hand-checked set stays the headline number.

Two filters keep the set honest as *known-item* retrieval, which is what
`evaluation.py` measures:

* a slug that merely repeats the category the clip was fetched under names a
  topic, not a clip. "cat sleeping" is the search term all twenty cat videos
  came from, so scoring it as known-item would count nineteen right answers
  as failures.
* very short slugs are topics for the same reason.

Targets are whole videos. The manifest says which clip a description belongs
to, never which second of it, and inventing a timestamp range would be
claiming precision nobody verified. So this set measures *video selection*;
timestamp accuracy is what the hand-labelled set is for.
"""

from __future__ import annotations

import json
import re
from collections import defaultdict
from pathlib import Path
from typing import Any, Mapping

# Below this, a slug is a topic rather than a description of one clip.
MIN_SLUG_WORDS = 3

_SLUG_RE = re.compile(r"/video/([a-z0-9-]+?)(?:-\d+)?/?$", re.IGNORECASE)


class ManifestError(Exception):
    """A manifest that cannot be turned into a usable eval set."""


def load_manifest(path: Path | str) -> dict[str, Any]:
    path = Path(path)
    if not path.is_file():
        raise ManifestError(f"manifest not found: {path}")
    try:
        payload = json.loads(path.read_text())
    except json.JSONDecodeError as exc:
        raise ManifestError(f"{path} is not valid JSON: {exc}") from exc
    if not isinstance(payload, dict) or not payload:
        raise ManifestError(f"{path} must be a non-empty object keyed by video id")
    return payload


def slug_of(url: str) -> str | None:
    """The human-written description in a Pexels video URL, or None.

    `.../video/woman-cracking-eggs-8503205/` -> "woman cracking eggs". The
    trailing numeric id is an identifier, not part of the description.
    """
    match = _SLUG_RE.search(url or "")
    if not match:
        return None
    return match.group(1).replace("-", " ").strip().lower() or None


def _normalise(text: str) -> str:
    return " ".join(text.lower().split())


def labels_from_manifest(manifest: Mapping[str, Any]) -> dict:
    """Build a labels payload in the shape `evaluation.load_labels` validates."""
    by_query: dict[str, list[dict]] = defaultdict(list)
    skipped_no_slug = 0
    skipped_category = 0
    skipped_short = 0

    for entry in manifest.values():
        if not isinstance(entry, dict):
            continue
        slug = slug_of(str(entry.get("url", "")))
        if not slug:
            skipped_no_slug += 1
            continue
        if len(slug.split()) < MIN_SLUG_WORDS:
            skipped_short += 1
            continue
        if _normalise(slug) == _normalise(str(entry.get("query", ""))):
            skipped_category += 1
            continue

        filename = entry.get("file")
        if not filename:
            skipped_no_slug += 1
            continue
        by_query[slug].append(
            {
                "video": str(filename),
                "start_sec": 0.0,
                "end_sec": float(entry.get("duration_sec", 0) or 0),
            }
        )

    if not by_query:
        raise ManifestError(
            "no usable descriptions in the manifest -- every entry was missing a "
            "slug, too short, or a restatement of its own category. Refusing to "
            "emit an eval set that would report 100% of nothing."
        )

    queries = [
        {
            "query": slug,
            # Several clips can share a description, and both are then correct
            # answers; one label with several targets says that, where two
            # labels would make each score the other as a miss.
            "targets": sorted(targets, key=lambda t: t["video"]),
        }
        for slug, targets in sorted(by_query.items())
    ]

    return {
        "_readme": (
            "GENERATED by scripts/make_corpus_labels.py from the corpus manifest -- "
            "do not hand-edit. These are WEAK supervision: the query is the "
            "uploader's own description of the clip, and nobody checked it against "
            "the frames. Use this set to COMPARE configurations, where a paired "
            "comparison cancels per-query noise. eval/labels.json is the "
            "hand-checked set and remains the headline number. Targets are whole "
            "videos, so this measures video selection, not timestamp accuracy."
        ),
        "_skipped": {
            "no_slug": skipped_no_slug,
            "too_short": skipped_short,
            "restates_category": skipped_category,
        },
        "queries": queries,
    }
